site_name: XcodePilot
site_url: https://xcodepilot.thriller.fun
site_dir: public
site_author: ThrillerOne
nav:
  - index.md
  - download.md
  - release_note.md

# Theme
theme:
  name: material
  # custom_dir: 'mkdocs-material/material'
  static_templates:
    - 404.html
  language: "zh"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: true
  search_index_only: true
  favicon: "favicon.ico"
  logo: "favicon_512x512.png"
  features:
    - navigation.tabs
    - navigation.instant
  font:
    text: "Fira Sans"
    code: "Fira Mono"

plugins:
  search:
    lang:
      - en
      - zh

# hooks:
#   - hooks/on_env.py

# Customization
extra:
  disqus: "XcodePilot"
  # copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: "on"
  manifest: "manifest.webmanifest"
  githash: ""
  analytics:
    provider: google
    # property: G-RJ87LG0EY1
    property: G-1MTP6RZ88K

extra_javascript:
  - "_static/js/math-csr.js?math-csr"
  - "_static/js/ad.js"

extra_css:
  - "_static/css/extra.css?v=14"

# Extensions
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
